<?php

/**
 * Model base class generated by the SDKGenerator\Generator.
 * Changes made to this file WILL NOT BE OVERWRITTEN when the generator is run.
 *
 */

namespace {{ namespace }};


class {{ class }} extends Base\{{ class }} {


}